import type { Locale } from "./types";

export const consistencyCopy = {
  fr: {
    chooseSide: "Face à reprendre",
    attemptsReached:
      "Le nombre de lectures autorisées est atteint pour une des faces. Choisissez une autre face disponible.",
    title: "Lectures à vérifier",
    detail:
      "Comparez ces informations au document original, puis reprenez la face concernée.",
    coverage: "Comparaisons des informations",
    coverageDetail:
      "Certaines vérifications sont limitées ou indisponibles. Une information absente ne confirme pas un accord.",
    coverageLabel: "Couverture des vérifications",
    namesLabel: "Noms",
    namesUnavailable:
      "Les noms ne sont pas comparables entre ces écritures. Aucune équivalence arabe–latin n’est supposée.",
    differentNumbers: "Ces numéros désignent des informations différentes. Leur égalité n’est pas attendue.",
    failed: "Divergence",
    warning: "À vérifier",
    not_checked: "Non vérifié",
    passed: "Concordant",
    mismatch: "Les lectures de ce champ ne correspondent pas.",
    warningDetail: "Les lectures présentent une différence ou une validation limitée.",
    unavailable: "Ce champ n’a pas pu être comparé : valeur absente, invalide ou écritures non comparables.",
    suggested: "Cette lecture se distingue des autres. Cela ne prouve pas qu’elle est incorrecte.",
    background: "La lecture de la face reçue se poursuit pendant la photo suivante.",
    phoneConflict: "Des lectures doivent être vérifiées",
    phoneDetail: "Choisissez sur l’ordinateur la face à reprendre. Les autres photos sont conservées.",
  },
  en: {
    chooseSide: "Side to retake",
    attemptsReached: "One side has reached its reading limit. Choose another available side.",
    title: "Readings need review",
    detail:
      "Compare these readings with the original document, then retake the affected side.",
    coverage: "Information comparisons",
    coverageDetail: "Some checks are limited or unavailable. A missing value does not confirm agreement.",
    coverageLabel: "Check coverage",
    namesLabel: "Names",
    namesUnavailable: "Names cannot be compared across these scripts. No Arabic–Latin equivalence is assumed.",
    differentNumbers: "These numbers represent different facts. They are not expected to match.",
    failed: "Mismatch",
    warning: "Review needed",
    not_checked: "Not checked",
    passed: "Matches",
    mismatch: "The readings for this field do not match.",
    warningDetail: "The readings differ or validation is limited.",
    unavailable: "This field could not be compared: a value is missing, invalid, or uses a different script.",
    suggested: "This reading differs from the others. That does not prove it is incorrect.",
    background: "The received side is being read while you take the next photo.",
    phoneConflict: "Some readings need review",
    phoneDetail: "Choose the side to retake on your computer. Other photos will be kept.",
  },
  ar: {
    chooseSide: "الوجه المراد إعادة تصويره",
    attemptsReached: "وصل أحد الأوجه إلى الحد المسموح للقراءة. اختر وجهًا آخر متاحًا.",
    title: "قراءات تحتاج إلى مراجعة",
    detail:
      "قارن هذه المعلومات بالوثيقة الأصلية ثم أعد تصوير الوجه المعني.",
    coverage: "مقارنة المعلومات",
    coverageDetail: "بعض الفحوص محدودة أو غير متاحة. غياب المعلومة لا يؤكد تطابقها.",
    coverageLabel: "تغطية الفحوص",
    namesLabel: "الأسماء",
    namesUnavailable: "لا يمكن مقارنة الأسماء بين هاتين الأبجديتين. لا يُفترض تكافؤ بين العربية واللاتينية.",
    differentNumbers: "تشير هذه الأرقام إلى معلومات مختلفة. لا يُتوقع تطابقها.",
    failed: "اختلاف",
    warning: "تحتاج إلى مراجعة",
    not_checked: "لم يتم التحقق",
    passed: "متطابق",
    mismatch: "قراءات هذا الحقل غير متطابقة.",
    warningDetail: "تختلف القراءات أو يكون التحقق محدودًا.",
    unavailable: "تعذرت مقارنة هذا الحقل: القيمة ناقصة أو غير صالحة أو مكتوبة بأبجدية غير قابلة للمقارنة.",
    suggested: "تختلف هذه القراءة عن القراءات الأخرى. هذا لا يثبت أنها خاطئة.",
    background: "تستمر قراءة الوجه المستلم أثناء تصوير الوجه التالي.",
    phoneConflict: "بعض القراءات تحتاج إلى مراجعة",
    phoneDetail: "اختر على الكمبيوتر الوجه الذي ستعيد تصويره. ستبقى الصور الأخرى محفوظة.",
  },
} satisfies Record<Locale, Record<string, string>>;
