import type { DocumentSide, Locale, ProcessingStage } from "./types";

export const journeyCopy = {
  fr: {
    secure: "Parcours documentaire sécurisé",
    startTitle: "Vos documents, vérifiés avec soin.",
    startDetail:
      "Choisissez les documents demandés. Prenez les photos avec votre téléphone, puis vérifiez les informations ici avant l’envoi.",
    start: "Commencer la vérification",
    invitation: "Ouvrez le lien sécurisé reçu de votre application pour commencer.",
    selectTitle: "Quels documents allez-vous présenter ?",
    selectDetail: "Choisissez les documents à présenter. Chaque face sera photographiée séparément.",
    fixedSelectionDetail:
      "Ces documents sont demandés pour cette vérification. Chaque face sera photographiée séparément.",
    selectAction: "Valider mon choix",
    selected: "sélectionnés",
    connectTitle: "Continuez avec votre téléphone",
    connectDetail:
      "Scannez ce QR code. Le téléphone prend uniquement les photos ; cette page suit leur traitement en direct.",
    pairedDetail:
      "Le téléphone est associé. Prenez la photo demandée sur celui-ci ; son état apparaît ici en direct. Si besoin, générez un autre QR code.",
    connected: "Téléphone associé",
    waitingPhone: "En attente du téléphone",
    reconnect: "Afficher un nouveau QR code",
    cameraTask: "Photo attendue",
    received: "Photo reçue",
    waiting: "En attente de la photo",
    processingTitle: "Lecture en cours",
    processingDetail: "Vous pouvez laisser le téléphone de côté. Les résultats apparaîtront ici automatiquement.",
    retrying: "Nouvelle tentative du serveur en cours",
    reviewTitle: "Vérifiez les informations lues",
    reviewDetail:
      "Les valeurs sont en lecture seule. Si une valeur est absente ou incorrecte, reprenez uniquement la face concernée.",
    missingTitle: "Certaines informations sont absentes ou invalides",
    missingDetail: "Choisissez la face à reprendre sur le téléphone. L’autre photo sera conservée.",
    confirm: "Confirmer ce document",
    retake: "Reprendre cette face",
    retakeInProgress: "Nouvelle photo en attente ou en cours de lecture",
    summaryTitle: "Tout est prêt pour l’envoi",
    summaryDetail:
      "Relisez une dernière fois les valeurs de chaque document. Vous pouvez encore reprendre une face avant de soumettre.",
    submit: "Soumettre mon dossier",
    submitted: "Dossier envoyé",
    submittedDetail: "Les documents ont été vérifiés et transmis à votre application.",
    return: "Terminer",
    failed: "La vérification n’a pas pu aboutir",
    failedDetail: "Revenez à l’application d’origine ou contactez son assistance pour recommencer.",
    retry: "Réessayer",
    loading: "Ouverture de votre session sécurisée…",
    unavailable: "Connexion temporairement indisponible. Nous essayons de rétablir le suivi.",
    sessionMissing:
      "Ce lien ne correspond plus à une session active. Demandez un nouveau lien à l’application d’origine.",
    step: "Étape",
    of: "sur",
    readOnly: "Valeurs extraites, non modifiables",
    missingValue: "Non lu",
    cameraReady: "Préparez votre document",
    cameraReadyDetail:
      "Placez la bonne face dans le cadre. La prise automatique démarre après cinq secondes de stabilité.",
    openCamera: "Ouvrir la caméra",
    phoneDone: "La suite se passe sur l’ordinateur",
    phoneDoneDetail: "La photo est envoyée. Gardez cette page ouverte : l’ordinateur pourra demander une autre face.",
    phoneWait: "Attendez les instructions sur l’ordinateur",
    phoneWaitDetail:
      "Le résultat est en cours de lecture ou de vérification. La caméra reste fermée pendant ce traitement.",
    phoneNext: "Face suivante",
    phoneFinished: "Toutes les photos sont reçues",
    front: "Recto",
    back: "Verso",
    single: "Page d’identité",
    allFields: "Valeurs du document",
    stage: {
      photos_received: "Photos reçues",
      quality_validated: "Qualité de la photo validée",
      ocr_reading: "Lecture OCR en cours",
      field_validation: "Vérification des champs",
    },
  },
  en: {
    secure: "Secure document journey",
    startTitle: "Your documents, carefully verified.",
    startDetail:
      "Choose the requested documents. Take photos on your phone, then review the information here before submitting.",
    start: "Start verification",
    invitation: "Open the secure link from your application to begin.",
    selectTitle: "Which documents will you provide?",
    selectDetail: "Choose the documents you will provide. Each side will be photographed separately.",
    fixedSelectionDetail:
      "These documents are required for this verification. Each side will be photographed separately.",
    selectAction: "Confirm my choice",
    selected: "selected",
    connectTitle: "Continue on your phone",
    connectDetail: "Scan this QR code. Your phone only takes photos; this page tracks processing live.",
    pairedDetail:
      "The phone is paired. Take the requested photo there; its progress appears here live. Generate another QR code if needed.",
    connected: "Phone paired",
    waitingPhone: "Waiting for phone",
    reconnect: "Show a new QR code",
    cameraTask: "Photo needed",
    received: "Photo received",
    waiting: "Waiting for photo",
    processingTitle: "Reading in progress",
    processingDetail: "You can set your phone aside. Results will appear here automatically.",
    retrying: "Server retry in progress",
    reviewTitle: "Review the information",
    reviewDetail: "Values are read-only. If one is missing or wrong, retake only the affected side.",
    missingTitle: "Some information is missing or invalid",
    missingDetail: "Choose the side to retake on your phone. The other photo will be kept.",
    confirm: "Confirm this document",
    retake: "Retake this side",
    retakeInProgress: "Waiting for or reading the new photo",
    summaryTitle: "Ready to submit",
    summaryDetail: "Review every document once more. You can still retake a side before submitting.",
    submit: "Submit my documents",
    submitted: "Documents submitted",
    submittedDetail: "Your documents have been verified and sent to your application.",
    return: "Finish",
    failed: "Verification could not be completed",
    failedDetail: "Return to the originating application or contact its support to start again.",
    retry: "Try again",
    loading: "Opening your secure session…",
    unavailable: "Connection temporarily unavailable. We are restoring live updates.",
    sessionMissing: "This link no longer opens an active session. Request a new link from the original application.",
    step: "Step",
    of: "of",
    readOnly: "Extracted values, read-only",
    missingValue: "Not read",
    cameraReady: "Prepare your document",
    cameraReadyDetail: "Place the correct side in the frame. Auto-capture starts after five seconds of stability.",
    openCamera: "Open camera",
    phoneDone: "Continue on your computer",
    phoneDoneDetail: "Your photo was sent. Keep this page open: the computer may request another side.",
    phoneWait: "Wait for instructions on your computer",
    phoneWaitDetail: "The result is being read or reviewed. The camera stays closed during processing.",
    phoneNext: "Next side",
    phoneFinished: "All photos received",
    front: "Front",
    back: "Back",
    single: "Identity page",
    allFields: "Document values",
    stage: {
      photos_received: "Photos received",
      quality_validated: "Photo quality checked",
      ocr_reading: "OCR reading in progress",
      field_validation: "Checking fields",
    },
  },
  ar: {
    secure: "مسار وثائق آمن",
    startTitle: "وثائقك، نتحقق منها بعناية.",
    startDetail: "اختر الوثائق المطلوبة. التقط الصور بهاتفك، ثم راجع المعلومات هنا قبل الإرسال.",
    start: "بدء التحقق",
    invitation: "افتح الرابط الآمن الذي وصلك من تطبيقك للبدء.",
    selectTitle: "ما الوثائق التي ستقدمها؟",
    selectDetail: "اختر الوثائق التي ستقدمها. سيتم تصوير كل وجه على حدة.",
    fixedSelectionDetail: "هذه الوثائق مطلوبة للتحقق. سيتم تصوير كل وجه على حدة.",
    selectAction: "تأكيد الاختيار",
    selected: "محددة",
    connectTitle: "تابع باستخدام هاتفك",
    connectDetail: "امسح رمز QR. الهاتف مخصص للتصوير فقط، وتتابع هذه الصفحة المعالجة مباشرة.",
    pairedDetail:
      "تم ربط الهاتف. التقط الصورة المطلوبة به وستظهر حالتها هنا مباشرة. يمكنك إنشاء رمز QR جديد عند الحاجة.",
    connected: "تم ربط الهاتف",
    waitingPhone: "بانتظار الهاتف",
    reconnect: "إظهار رمز QR جديد",
    cameraTask: "الصورة المطلوبة",
    received: "تم استلام الصورة",
    waiting: "بانتظار الصورة",
    processingTitle: "القراءة جارية",
    processingDetail: "يمكنك ترك الهاتف جانبًا. ستظهر النتائج هنا تلقائيًا.",
    retrying: "تجري محاولة جديدة على الخادم",
    reviewTitle: "راجع المعلومات المقروءة",
    reviewDetail: "القيم للقراءة فقط. إذا كانت قيمة ناقصة أو خاطئة، أعد تصوير الوجه المعني فقط.",
    missingTitle: "بعض المعلومات ناقصة أو غير صالحة",
    missingDetail: "اختر الوجه الذي ستعيد تصويره. ستبقى الصورة الأخرى محفوظة.",
    confirm: "تأكيد هذه الوثيقة",
    retake: "إعادة تصوير هذا الوجه",
    retakeInProgress: "بانتظار الصورة الجديدة أو قراءتها",
    summaryTitle: "ملفك جاهز للإرسال",
    summaryDetail: "راجع قيم كل وثيقة مرة أخيرة. لا يزال بإمكانك إعادة تصوير أحد الأوجه قبل الإرسال.",
    submit: "إرسال ملفي",
    submitted: "تم إرسال الملف",
    submittedDetail: "تم التحقق من وثائقك وإرسالها إلى تطبيقك.",
    return: "إنهاء",
    failed: "تعذر إكمال التحقق",
    failedDetail: "ارجع إلى التطبيق الأصلي أو تواصل مع دعمه للبدء من جديد.",
    retry: "إعادة المحاولة",
    loading: "جارٍ فتح جلستك الآمنة…",
    unavailable: "الاتصال غير متاح مؤقتًا. نحاول استعادة التحديثات المباشرة.",
    sessionMissing: "لم يعد هذا الرابط مرتبطًا بجلسة نشطة. اطلب رابطًا جديدًا من التطبيق الأصلي.",
    step: "المرحلة",
    of: "من",
    readOnly: "القيم المستخرجة غير قابلة للتعديل",
    missingValue: "لم يُقرأ",
    cameraReady: "حضّر وثيقتك",
    cameraReadyDetail: "ضع الوجه الصحيح داخل الإطار. يبدأ الالتقاط التلقائي بعد خمس ثوانٍ من الثبات.",
    openCamera: "فتح الكاميرا",
    phoneDone: "أكمل على الكمبيوتر",
    phoneDoneDetail: "أُرسلت الصورة. أبقِ هذه الصفحة مفتوحة، فقد يُطلب تصوير وجه آخر.",
    phoneWait: "انتظر التعليمات على الكمبيوتر",
    phoneWaitDetail: "النتيجة قيد القراءة أو المراجعة. تبقى الكاميرا مغلقة أثناء المعالجة.",
    phoneNext: "الوجه التالي",
    phoneFinished: "تم استلام جميع الصور",
    front: "الوجه الأمامي",
    back: "الوجه الخلفي",
    single: "صفحة الهوية",
    allFields: "قيم الوثيقة",
    stage: {
      photos_received: "تم استلام الصور",
      quality_validated: "تم التحقق من جودة الصورة",
      ocr_reading: "قراءة النص جارية",
      field_validation: "التحقق من الحقول",
    },
  },
} satisfies Record<Locale, Record<string, string | Record<ProcessingStage, string>>>;

export function sideLabel(locale: Locale, side: DocumentSide): string {
  return journeyCopy[locale][side];
}

const actionErrors: Record<string, Record<Locale, string>> = {
  document_not_ready: {
    fr: "La lecture n’est pas terminée. Patientez quelques instants.",
    en: "Reading is not finished yet. Please wait.",
    ar: "لم تنته قراءة الوثيقة بعد. يرجى الانتظار.",
  },
  session_not_ready: {
    fr: "Tous les documents doivent être confirmés avant l’envoi.",
    en: "Confirm every document before submitting.",
    ar: "يجب تأكيد جميع الوثائق قبل الإرسال.",
  },
  document_locked: {
    fr: "Terminez d’abord le document en cours.",
    en: "Finish the current document first.",
    ar: "أكمل الوثيقة الحالية أولاً.",
  },
  session_closed: {
    fr: "Cette session est terminée. Revenez à l’application d’origine.",
    en: "This session has ended. Return to the original application.",
    ar: "انتهت هذه الجلسة. ارجع إلى التطبيق الأصلي.",
  },
  submission_limit_reached: {
    fr: "Le nombre de tentatives autorisées est atteint.",
    en: "The allowed number of attempts has been reached.",
    ar: "تم بلوغ عدد المحاولات المسموح بها.",
  },
  backend_unavailable: {
    fr: "Le service est momentanément indisponible. Réessayez.",
    en: "The service is temporarily unavailable. Please retry.",
    ar: "الخدمة غير متاحة مؤقتًا. أعد المحاولة.",
  },
};

export function journeyError(locale: Locale, code: unknown): string {
  return actionErrors[String(code)]?.[locale] ?? journeyCopy[locale].unavailable;
}

const recaptureReasons: Record<string, Record<Locale, string>> = {
  document_not_verified: {
    fr: "Le document ou la face attendue n’a pas été reconnu. Vérifiez la bonne face et reprenez la photo.",
    en: "The expected document or side was not recognized. Check the side and retake the photo.",
    ar: "لم يتم التعرف على الوثيقة أو الوجه المطلوب. تحقق من الوجه وأعد التصوير.",
  },
  nin_mismatch: {
    fr: "Les numéros d’identité ne correspondent pas. Reprenez les documents demandés.",
    en: "The identity numbers do not match. Retake the requested documents.",
    ar: "أرقام الهوية غير متطابقة. أعد تصوير الوثائق المطلوبة.",
  },
  dateOfBirth_mismatch: {
    fr: "Les dates de naissance ne correspondent pas. Reprenez les documents demandés.",
    en: "The birth dates do not match. Retake the requested documents.",
    ar: "تواريخ الميلاد غير متطابقة. أعد تصوير الوثائق المطلوبة.",
  },
};

export function recaptureReason(locale: Locale, reasonCode: string | null): string | undefined {
  return reasonCode ? recaptureReasons[reasonCode]?.[locale] : undefined;
}

const fieldNames: Record<string, [string, string, string]> = {
  documentValidation: ["Contrôles du document", "Document checks", "فحوص الوثيقة"],
  lastNameLatin: ["Nom (latin)", "Last name (Latin)", "اللقب (لاتيني)"],
  firstNameLatin: ["Prénom (latin)", "First name (Latin)", "الاسم (لاتيني)"],
  lastNameArabic: ["Nom (arabe)", "Last name (Arabic)", "اللقب (عربي)"],
  firstNameArabic: ["Prénom (arabe)", "First name (Arabic)", "الاسم (عربي)"],
  nin: ["Numéro d’identification national", "National identification number", "رقم التعريف الوطني"],
  documentNumber: ["Numéro du document", "Document number", "رقم الوثيقة"],
  dateOfBirth: ["Date de naissance", "Date of birth", "تاريخ الميلاد"],
  expiryDate: ["Date d’expiration", "Expiry date", "تاريخ انتهاء الصلاحية"],
  surname_latin: ["Nom (latin)", "Last name (Latin)", "اللقب (لاتيني)"],
  given_name_latin: ["Prénom (latin)", "First name (Latin)", "الاسم (لاتيني)"],
  surname_ar: ["Nom (arabe)", "Last name (Arabic)", "اللقب (عربي)"],
  given_name_ar: ["Prénom (arabe)", "First name (Arabic)", "الاسم (عربي)"],
  document_number: ["Numéro du document", "Document number", "رقم الوثيقة"],
  date_of_birth: ["Date de naissance", "Date of birth", "تاريخ الميلاد"],
  date_of_expiry: ["Date d’expiration", "Expiry date", "تاريخ انتهاء الصلاحية"],
  date_of_issue: ["Date de délivrance", "Issue date", "تاريخ الإصدار"],
  place_of_birth: ["Lieu de naissance", "Place of birth", "مكان الميلاد"],
  nationality: ["Nationalité", "Nationality", "الجنسية"],
  sex: ["Sexe", "Sex", "الجنس"],
  issuing_authority: ["Autorité de délivrance", "Issuing authority", "جهة الإصدار"],
  mrz_line_1: ["Ligne MRZ 1", "MRZ line 1", "سطر القراءة الآلية ١"],
  mrz_line_2: ["Ligne MRZ 2", "MRZ line 2", "سطر القراءة الآلية ٢"],
  mrz_line_3: ["Ligne MRZ 3", "MRZ line 3", "سطر القراءة الآلية ٣"],
  date_of_birth_printed: ["Naissance (imprimée)", "Birth date (printed)", "تاريخ الميلاد المطبوع"],
  date_of_issue_printed: ["Délivrance (imprimée)", "Issue date (printed)", "تاريخ الإصدار المطبوع"],
  date_of_expiry_printed: ["Expiration (imprimée)", "Expiry date (printed)", "تاريخ الانتهاء المطبوع"],
  place_of_birth_ar: ["Lieu de naissance (arabe)", "Place of birth (Arabic)", "مكان الميلاد بالعربية"],
  place_of_birth_latin: ["Lieu de naissance (latin)", "Place of birth (Latin)", "مكان الميلاد باللاتينية"],
  issuing_authority_ar: ["Autorité de délivrance (arabe)", "Issuing authority (Arabic)", "جهة الإصدار بالعربية"],
  issuing_authority_latin: ["Autorité de délivrance (latin)", "Issuing authority (Latin)", "جهة الإصدار باللاتينية"],
  issuing_country: ["Pays de délivrance", "Issuing country", "بلد الإصدار"],
  blood_group: ["Groupe sanguin", "Blood group", "فصيلة الدم"],
  license_number: ["Numéro de permis", "Licence number", "رقم رخصة السياقة"],
  passport_number: ["Numéro de passeport", "Passport number", "رقم جواز السفر"],
  personal_number: ["Numéro personnel", "Personal number", "الرقم الشخصي"],
  serial_number: ["Numéro de série", "Serial number", "الرقم التسلسلي"],
  document_type: ["Type de document", "Document type", "نوع الوثيقة"],
  categories: ["Catégories", "Categories", "الفئات"],
  category_entries: ["Catégories et validités", "Categories and validity", "الفئات والصلاحية"],
  restrictions: ["Restrictions", "Restrictions", "القيود"],
};

export function fieldLabel(locale: Locale, key: string): string {
  const clean = key.replace(/^(front|back)_/, "");
  const label = fieldNames[key] ?? fieldNames[clean];
  if (label) return label[{ fr: 0, en: 1, ar: 2 }[locale]];
  return clean.replace(/_/g, " ").replace(/([a-z])([A-Z])/g, "$1 $2");
}
